# Generated by Django 2.2.6 on 2019-10-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(default='Default Client', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.CharField(default='Default PM', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_writeup',
            field=models.TextField(default='No writeup'),
            preserve_default=False,
        ),
    ]
