# Generated by Django 2.2.6 on 2019-10-29 18:36

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20191027_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='client_contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='project',
            name='con_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='construction end date'),
        ),
        migrations.AddField(
            model_name='project',
            name='con_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='construction start date'),
        ),
        migrations.AddField(
            model_name='project',
            name='des_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='design end date'),
        ),
        migrations.AddField(
            model_name='project',
            name='des_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='design start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_writeup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
