# Generated by Django 2.2.6 on 2019-10-29 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20191029_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{0,9}$')]),
        ),
    ]
