# Generated by Django 2.2.6 on 2019-10-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20191029_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='con_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='construction cost'),
        ),
    ]
