# Generated by Django 2.2.6 on 2020-02-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_con_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='des_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='design fee'),
        ),
    ]
