# Generated by Django 2.2.6 on 2020-02-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_des_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='con_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='construction end date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='con_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='construction start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='des_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='design end date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='des_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='design start date'),
        ),
    ]
