# Generated by Django 2.2.6 on 2020-02-02 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200201_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_email',
            field=models.EmailField(blank=True, max_length=200, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
