# Generated by Django 2.2.6 on 2020-02-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20200201_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='con_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='construction cost'),
        ),
        migrations.AlterField(
            model_name='project',
            name='des_fee',
            field=models.IntegerField(blank=True, null=True, verbose_name='design fee'),
        ),
    ]
