# Generated by Django 2.2.6 on 2019-11-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
