# Generated by Django 2.2.6 on 2019-11-10 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0004_auto_20191109_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_date', models.DateTimeField()),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='council.Department')),
            ],
            options={
                'ordering': ('department', 'agenda_date'),
            },
        ),
    ]
