# Generated by Django 2.2.6 on 2019-11-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0005_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='agenda_date',
            field=models.DateField(),
        ),
    ]
