# Generated by Django 2.2.6 on 2019-11-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0007_auto_20191110_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='agenda_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
