# Generated by Django 2.2.6 on 2019-11-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0008_agenda_agenda_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='agenda_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='agenda_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='agendas_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
