# Generated by Django 2.2.6 on 2019-11-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0010_auto_20191119_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawler',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
