# Generated by Django 2.2.6 on 2019-11-21 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0012_auto_20191120_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawler',
            name='department',
        ),
        migrations.AddField(
            model_name='crawler',
            name='department',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='crawlers', to='council.Department'),
            preserve_default=False,
        ),
    ]
