# Generated by Django 2.2.6 on 2019-11-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0013_auto_20191120_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawler',
            name='department',
        ),
        migrations.AddField(
            model_name='crawler',
            name='department',
            field=models.ManyToManyField(related_name='crawlers', to='council.Department'),
        ),
    ]
