# Generated by Django 2.2.6 on 2020-01-04 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0014_auto_20191120_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawler',
            options={'ordering': ('crawler_name', 'date_added')},
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('hl_start', models.PositiveIntegerField()),
                ('hl_end', models.PositiveIntegerField()),
                ('hl_category', models.CharField(blank=True, max_length=200, null=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='council.Agenda')),
            ],
        ),
    ]
