# Generated by Django 2.2.6 on 2020-01-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0015_auto_20200103_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='hl_category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='hl_end',
            field=models.PositiveIntegerField(verbose_name='highlight end'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='hl_start',
            field=models.PositiveIntegerField(verbose_name='highlight start'),
        ),
    ]
