# Generated by Django 2.2.6 on 2020-01-04 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0016_auto_20200103_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ('agenda__department__agency_name', 'agenda__department_name', 'pk')},
        ),
    ]
