# Generated by Django 2.2.6 on 2020-01-04 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0017_auto_20200103_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlight',
            options={},
        ),
    ]
