# Generated by Django 2.2.6 on 2020-01-04 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0018_auto_20200103_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ('agenda__department_name', 'pk')},
        ),
    ]
