# Generated by Django 2.2.6 on 2020-01-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0019_auto_20200103_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ('agenda__department_name', 'agenda__department__agency_name', '__str__')},
        ),
    ]
