# Generated by Django 2.2.6 on 2020-01-04 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0020_auto_20200103_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlight',
            options={},
        ),
    ]
