# Generated by Django 2.2.6 on 2020-01-04 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0021_auto_20200103_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hl_category_name', models.CharField(default='Default', max_length=200, verbose_name='category name')),
                ('date_added', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw_category_name', models.CharField(default='Default', max_length=200, verbose_name='category name')),
                ('date_added', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw_text', models.CharField(default='Default', max_length=200, verbose_name='keyword')),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('kw_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='council.KeywordCategory')),
            ],
        ),
    ]
