# Generated by Django 2.2.6 on 2020-01-04 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0022_highlightcategory_keyword_keywordcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlightcategory',
            options={'verbose_name_plural': 'Highlight Categories'},
        ),
        migrations.AlterModelOptions(
            name='keywordcategory',
            options={'verbose_name_plural': 'Keyword Categories'},
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='hl_category',
        ),
        migrations.AlterField(
            model_name='keyword',
            name='kw_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='council.KeywordCategory', verbose_name='keyword category'),
        ),
    ]
