# Generated by Django 2.2.6 on 2020-01-04 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0023_auto_20200104_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='council.HighlightCategory'),
        ),
    ]
