# Generated by Django 2.2.6 on 2020-01-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0024_highlight_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Default', max_length=200)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
