# Generated by Django 2.2.6 on 2020-01-04 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0025_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='category',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='kw_category',
        ),
        migrations.AddField(
            model_name='keyword',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='council.Category'),
        ),
    ]
