# Generated by Django 2.2.6 on 2020-01-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0027_highlight_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyphrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kp_text', models.CharField(default='Default', max_length=200, verbose_name='keyphrase')),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='keyphrases', to='council.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='HighlightCategory',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='category',
        ),
        migrations.DeleteModel(
            name='KeywordCategory',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
