# Generated by Django 2.2.6 on 2020-01-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0028_auto_20200104_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ('department__agency_name', 'department', '-agenda_date')},
        ),
        migrations.AddField(
            model_name='agenda',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
