# Generated by Django 2.2.6 on 2020-03-02 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0030_auto_20200121_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawler',
            old_name='department',
            new_name='departments',
        ),
    ]
