# Generated by Django 2.2.6 on 2020-03-09 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0031_auto_20200302_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawler',
            name='departments',
        ),
        migrations.AddField(
            model_name='department',
            name='crawler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='council.Crawler'),
            preserve_default=False,
        ),
    ]
