# Generated by Django 2.2.6 on 2020-04-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0033_auto_20200404_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyphrase',
            options={'ordering': ('phrase', 'date_added')},
        ),
        migrations.RenameField(
            model_name='highlight',
            old_name='hl_end',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='highlight',
            old_name='hl_start',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='keyphrase',
            old_name='kp_text',
            new_name='phrase',
        ),
    ]
