# Generated by Django 2.2.6 on 2020-04-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0034_auto_20200404_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
    ]
