# Generated by Django 2.2.6 on 2020-04-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0037_auto_20200408_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ('pk', 'date_added')},
        ),
    ]
