# Generated by Django 2.2.6 on 2020-04-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0038_auto_20200408_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Converter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name', 'date_added'),
            },
        ),
    ]
