# Generated by Django 3.0.5 on 2020-05-06 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0040_department_converter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ('department__agency', 'department', '-agenda_date')},
        ),
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ('agenda__department__agency', 'agenda__department', 'pk')},
        ),
    ]
