# Generated by Django 3.0.5 on 2020-05-07 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0041_auto_20200505_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ('department__agency', 'department', 'agenda_date')},
        ),
    ]
